# Exclude additional directories.
extend-exclude = [
    ".*"
]

[lint]
preview = true # to enable/disable features in preview
extend-select = [
	"C4", # flake8-comprehensions [Rules | Ruff](https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4)
    "SIM", # flake8-simplify [Rules | Ruff](https://docs.astral.sh/ruff/rules/#flake8-simplify-sim)
    "TC", # (formerly TCH) flake8-type-checking [Rules | Ruff](https://docs.astral.sh/ruff/rules/#flake8-type-checking-tc)
    "PL", # Pylint [Rules | Ruff](https://docs.astral.sh/ruff/rules/#pylint-pl)
    "N", # pep8-naming [Rules | Ruff](https://docs.astral.sh/ruff/rules/#pep8-naming-n)
    "D", # pydocstyle [Rules | Ruff](https://docs.astral.sh/ruff/rules/#pydocstyle-d)
    "DOC", # pydoclint [Rules | Ruff](https://docs.astral.sh/ruff/rules/#pydoclint-doc) 
	"ANN", # flake8-annotations [Rules | Ruff](https://docs.astral.sh/ruff/rules/#flake8-annotations-ann): Type hints enforcement for fct prototypes
    # "S", # flake8-bandit [Rules | Ruff](https://docs.astral.sh/ruff/rules/#flake8-bandit-s): Security rules
]
extend-ignore = [
    "D206", # docstring-tab-indentation: Docstring should be indented with spaces, not tabs
    "D413", # missing-blank-line-after-last-section: Missing blank line after last section ("{name}")
    "D101", # undocumented-public-class: Missing docstring in public class
    "D102", # undocumented-public-method: Missing docstring in public method
    "D107", # undocumented-public-init: Missing docstring in __init__
    "D213", # first-line summary in docstring
    "D203", # incorrect-blank-line-before-class
]

[lint.pydocstyle]
convention = "google"  # Accepts: "google", "numpy", or "pep257".

[format]
preview = true # to enable/disable features in preview
indent-style = "tab"

